export { default as Home } from '../pages/Home/Home';
export { default as NavBar } from './NavBar/NavBar';
export { default as Recipes } from './Recipes/Recipes';
export { default as Recipe } from './Recipe/Recipe';
export { default as Modal } from './Modal/Modal';
export { default as RecipeDetail } from './RecipeDetail/RecipeDetail';
export { default as Landing } from '../pages/Landing/Landing';
export { default as BgAnimation } from './BgAnimation/BgAnimation';
export { default as Loading } from './Loading/Loading';